version: 2
project_name: spike

before:
  hooks:
    - go mod tidy

builds:
  - id: spike
    main: ./cmd/spike
    binary: spike
    ldflags:
      - -X "github.com/ayuxsec/spike/pkg/version.Version={{.Version}}"
      # - -s -w
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  -
    formats: [ binary ]
    name_template: "{{ .Binary}}.{{ .Os }}.{{ .Arch }}"

release:
  github:
    owner: ayuxsec
    name: spike