tools:
    httpx:
        threads: 25
        screenshot: false
        cmd_timeout_in_second: 900
    subfinder:
        threads: 10
        enabled: true
        cmd_timeout_in_second: 900
    katana:
        enabled: true
        threads: 10
        crawl_depth: 3
        max_crawl_time: 10m
        parallelism_threads: 10
        headless: false
        no_sandbox: false
        cmd_timeout_in_second: 900
    gau:
        enabled: true
        threads: 10
        cmd_timeout_in_second: 900
    nuclei:
        threads: 25
        template_settings:
            generic: true
            dast: true
            headless: false
        template_paths:
            generic:
                include:
                    - http/
                    - cloud/
                    - javascript/
                    - dns/
                    - ssl/
                    - network/
                    - http/cves/2024
                    - http/cves/2023
                    - http/cves/2022
                    - http/cves/2021
                    - http/cves/2020
                exclude:
                    - http/cves/
                exclude_severity:
                    - info
            dast:
                include:
                    - dast/
                exclude:
                    - ""
                exclude_severity:
                    - info
        cmd_timeout_in_second: 900
    cachex:
        enabled: true
        threads: 10
        cmd_timeout_in_second: 900
reporter:
    telegram:
        enabled: false
        bot_token: ""
        chat_id: 0
        request_timeout: 10
